### PR TITLE
Include queried module names with distribution reports

### PR DESCRIPTION
**Pull request by reneeb**
… JSON output

One might have »requires 'LWP::UserAgent'« in the cpan file or uses »cpan-audit --json module LWP::UserAgent« and wonders why 'libwww-perl' is listed with advisories. This commit adds a 'listed_modules' key for the dist. It changes the json, it doesn't have an impact on the standard output

### CODE REVIEW

**Comment by briandfoy** [comment]
I don't quite understand this. Can you show an example of how you would use this?

Also, this needs:

- [ ] tests
- [ ] documentation

**Comment by reneeb** [comment]
Below you'll find a short example where the `cpan-audit` command *module* is used. The module that is checked is *LWP::UserAgent*, but `cpan-audit` reports vulnerabilities for *libwww-perl*. This might be confusing for less experienced users.

With the PR applied there is the key *listed_modules*. There you can see the *LWP::UserAgent*, the user passed to `cpan-audit`.

```
$ cpan-audit --json module LWP::UserAgent | jq
{
  "errors": [],
  "meta": {
    ...
  },
  "dists": {
    "libwww-perl": {
      "listed_modules": [
        "LWP::UserAgent"
      ],
      "version": "Any",
      "advisories": [
```

Another example:

```
$ cpan-audit --json modules Mojo::File Mojo::UserAgent LWP::UserAgent | jq
{
  "errors": [],
  "meta": {
    ...
  },
  "dists": {
    "libwww-perl": {
      "listed_modules": [
        "LWP::UserAgent"
      ],
      "version": "Any",
      "advisories": [...]
    },
    "Mojolicious": {
      "version": "Any",
      "listed_modules": [
        "Mojo::File",
        "Mojo::UserAgent"
      ]
    }
  }
}
```

I'll add tests and documentation soon.

**Comment by reneeb** [comment]
> Instead of "listed", how about "queried"?

This sounds better!

**Comment by reneeb** [comment]
tests and documentation added...

**Comment by briandfoy** [comment]
Ok, I see the changes, but give me a few days to catch up with some other things.

**Comment by briandfoy** [comment]
Looks good. Thanks,

**Pull request merged**
