### PR TITLE
stability improvements to util/generate

### PR DESCRIPTION
**Pull request by garu**
Hey brian!

This patch fixes some runtime warnings and other minor issues, but also fixes an outstanding issue regarding how data was being collected from MetaCPAN API. Turns out many of the CPANSA-listed distributions did not map directly to MetaCPAN's index and were causing all sorts of weird behavior.

Overall, if this patch is applied, util/generate is expected to be faster, provide extra troubleshoot information during runtime, and yield more consistent results.

Thank you!

### CODE REVIEW

**Comment by briandfoy** [comment]
There's a lot of stuff going on here, and I don't know why you've made some of the changes.

Can  you break this into individual issues that cover only one problem, and explain the problem? In general, that makes it much easier for me to review.

I see that you used `die` a few times. I don't think that's a good idea.

**Comment by oalders** [comment]
@garu this fails the appveyor build.

**Comment by garu** [comment]
huh. I'll investigate as soon as I land!

**Comment by briandfoy** [comment]
See [my comment]((https://github.com/briandfoy/cpan-security-advisory/pull/126#issuecomment-1528915200) in #126.

I think it's better that MetaCPAN ignore `util/generate` and should deal with the reports directly to get anything it needs.

**Comment by garu** [comment]
Agreed. I'll make a separate repository that fetches reports and do their thing. Still, this patch contains some improvements that may be useful. I'll close this PR and send one for each so you can decide on each of them individually.

Thanks!

**Comment by briandfoy** [comment]
I've cherry-picked most of this and made the adjustments it needed. Thanks,

**Pull request closed without merging**
