### PR TITLE
Add --exitnormal option to force a normal exit value even if advisories were found

### PR DESCRIPTION
**Pull request by mariominati22**
We want to use CPAN::Audit within Gitlab piplelines. All our pipelines are run with 'set -e' activated. So a non zero exit code, stops the pipeline right away. As we use the json output for further pasrsing and processing to put the data into the Gitlab Sast scanning reports, we need to get a zero exit code.

### CODE REVIEW

**Comment by mariominati22** [comment]
Sorry for repushing the doc changes. I have no idea why this happend as I synced the repos before adding the new code...

**Comment by briandfoy** [comment]
This sort of change for a specific use case complicates things quite a bit since it needs to be carried through as a special case in all future development.

Can you show me the way that you are using this and why you can't handle this in the shell by checking the exit code, or wrapping this with your own shell script to exit in any particular way that you want for your particular use?

**Review by briandfoy — CHANGES_REQUESTED** [review]
I haven't convinced myself this is a good idea, and I still think that this is something that a workflow should handle on its own. But, having said that, this should be called `--exit-zero` and should have its own constant for that so it doesn't constrain unrelated parts of the code to this special case.

If you want to hold off on that until I decide, that's fine.

**Comment by mariominati22** [comment]
> I haven't convinced myself this is a good idea, and I still think that this is something that a workflow should handle on its own. But, having said that, this should be called `--exit-zero` and should have its own constant for that so it doesn't constrain unrelated parts of the code to this special case.

I have to smile, I named it exitzero in the first...

**Comment by briandfoy** [comment]
Would something like this work for your case?

    cpan-audit installed --exclude-file /cpan-audit-ignored-cves --fresh --verbose --perl && true

I'm heavily leaning toward the side that if you want to ignore an exit code, use the existing shell features that let you do that.

But, this also means that you'd ignore all other errors unrelated to the number of advisories found, and that isn't good either.

**Comment by mariominati22** [comment]
> Would something like this work for your case?
> 
> ```
> cpan-audit installed --exclude-file /cpan-audit-ignored-cves --fresh --verbose --perl && true
> ```
> 
> I'm heavily leaning toward the side that if you want to ignore an exit code, use the existing shell features that let you do that.
> 
> But, this also means that you'd ignore all other errors unrelated to the number of advisories found, and that isn't good either.

The last part is why we wouldn't see real errors, so this could not be a working solution in our case.

**Comment by briandfoy** [comment]
I've convinced myself this is a good idea. Make the changes I requested with `--exit-zero` and I'll merge this.

**Comment by mariominati22** [comment]
> I've convinced myself this is a good idea. Make the changes I requested with `--exit-zero` and I'll merge this.

That is nice, Thank you!

I've checked in the changes.

**Review by briandfoy — APPROVED** [review]

**Comment by mariominati22** [comment]
Thanks a lot :-)

**Pull request merged**
